### ISSUE TITLE
Lab2

### ISSUE THREAD

**Issue by lasbio** [zhiznenyj/DBLabSSAU#1]
1. Task 7 - по заданию должны быть выбраны только объекты. комментарий к заданию записан не точно, из-за этого и ошибка.
2. Task 9 -  (а) зачем записывать два отдельных условия (= и >) для одного и того же выражения; (б) зачем по отдельности записывать условия на год и месяц, если задано пороговое условие на конкретную дату - разве нельзя записать условие сравнения дат, без вычленения их составляющих.
3. Task 10 - не верно. По заданию отобрать 10, потом отсортировать. У вас отсортировать, потом отобрать 10.
4. Task 12 - не верно, начиная с комментария. В задании требуется найти дату последней регистрации (т.е. cамую позднюю), а не последнего по списку в members.
5. Task 14 - не верно, т.к. monthlymaintenance это стоимость обслуживания объекта, а не его стоимость. Кроме этого Ваш скрипт очень непроизводительный, т.к.  SELECT  ... FROM ... WHERE... ORDER BY.... LIMIT .... работает следующим образом:
- сначала оптимизатор сервера выбирает индексы, по которым будет идти фильтрация (WHERE);
- затем по этим индексам в память сервера будут извлечены все поля SELECT  по критериям из  WHERE;
- затем будет проведена сортировка записей по критериям ORDER BY;
- затем клиенту из этих записей в памяти сервера будут возвращено то их количество, которое задано в LIMIT.
Поэтому получается, что вы вызываете в память дважды ВСЕ записи из таблицы, чтобы затем вернуть пользователю только две, хотя можно сразу записать SELECT так, чтобы отбиралось в память только 2 записи. 
Численный пример для равнения. Пусть в таблице 120 млн. записей и на вызов 1 записи в память в среднем тратится 0.1 мсек.  Тогда, даже пренебрегая затратами времени на сортировку получаем 0.1 мсек * 120 млн = 12 сек.  А если записать условия так, что будут выбираться 2 записи, то будет затрачено всего 0.2 мсек. Предположим что ваш скрипт запускается при каждом обращении с серверу от любого клиента, а всего у сервиса в среднем 600 клиентов в день.  Получаем, что сервер будут в сутки занят на "никчемные" действия  12 сек * 600 = 2 часа. Итого, 1/12 времени сервер будут "молотить" бессмысленно. Предположим, что обслуживание сервера стоит 240 тыс. руб в год (электричество + программисты + ...). Тогда, получается, что ежегодно выбрасывается на ветер 20 тыс. рублей.

**Comment by zhiznenyj** [comment]
Здравствуйте, постарался исправить ошибки

**Comment by lasbio** [comment]
Task 7 - не выполнено.
Task 9 - не верно. По заданию надо выводить только членов, в не все записи после такой то даты.
Task 10 - не верно. По заданию отобрать 10, потом отсортировать. У вас отсортировать, потом отобрать 10. LIMIT- последняя операция (после ORDER BY).
Task 12 - не верно. У Вас выведена дата последней записи в таблице (с самым большим memid), а не  дата последней регистрации.

**Comment by zhiznenyj** [comment]
Исправил 7, 9, 10, 12

**Comment by lasbio** [comment]
1. Все, что не входит в проект должно быть в gitignore.

**Comment by zhiznenyj** [comment]
В gitignore. добавил, файлы удалил
