### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [zhiznenyj/DBLabSSAU#2]
1 Задание 1 - что будет, если в базе будут два  David Farrell (однофамильцы)?
2. Задания 4 -7 - не выполнены.

**Comment by zhiznenyj** [comment]
Доделал 4-7
Касательно первого:
Если у участника будут совпадать ИМЯ и ФАМИЛИЯ (David Farrell - полные тёзки), то выведет и его
Если у участника будет совпадать лишь ФАМИЛИЯ (однофамильцы), то его по запросу не выведет

**Comment by lasbio** [comment]
7 - скрипт выводит 29 записей, а в базе зарегистрировано 30 членов.

**Comment by zhiznenyj** [comment]
Теперь выводит правильно) 30

**Comment by lasbio** [comment]
7 - не верно.  Вместе с гостем в members 31 запись. По заданию Вам надо вывести только членов. Советую обратить внимание, что в вашем скрипте выводится 3 Смита, а в базе зарегистрировано 4.

**Comment by zhiznenyj** [comment]
Вроде понял - исправил
